# Generated by Django 4.0.6 on 2022-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_description_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN REVIEW', 'In Review'), ('DONE', 'Done')], default='PENDING', max_length=10),
        ),
    ]
